### ISSUE TITLE
Issue with PNG template

### ISSUE THREAD

**Issue by especially-relative** [twstokes/door_detect#1]
Hello!

I seem to be having issues with the png template. I am not sure, but it appears that the shape.templateImage of my template gets loaded incorrectly. The value right before a stack-trace is thrown is:

[[0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 ...,
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]]

This feels wrong, but I don't know enough about openCV to tell what went wrong. Stack trace is below. Over the next few weekends I'll poke at this as time permits, and post back/close issue if/when I figure it out.

OpenCV Error: Assertion failed (s >= 0) in setSize, file /builddir/build/BUILD/opencv-2.4.5/modules/core/src/matrix.cpp, line 116
Fatal error.
/builddir/build/BUILD/opencv-2.4.5/modules/core/src/matrix.cpp:116: error: (-215) s >= 0 in function setSize

Traceback (most recent call last):
  File "example.py", line 27, in <module>
    currentState = detector.detectState(inputImage)
  File "/home/$USER/door_detect/door_detect/detector.py", line 67, in detectState
    shapesDict = self.findShapes(inputImage)
  File "/home/$USER/door_detect/door_detect/detector.py", line 57, in findShapes
    self.detectAndOverlay(image, newShape)
  File "/home/$USER/door_detect/door_detect/detector.py", line 26, in detectAndOverlay
    result = cv2.matchTemplate(imageGray, shape.templateImage, cv2.TM_CCOEFF_NORMED)
error: /builddir/build/BUILD/opencv-2.4.5/modules/core/src/matrix.cpp:116: error: (-215) s >= 0 in function setSize

**Comment by twstokes** [comment]
Sorry for the delay, I need to turn on GitHub notifications.

Are you creating your templates from the raw output of the webcam? I grabbed a still from the webcam and cut out the templates from that picture. They ended up being a small portion of the image (this will vary depending on the distance of the shape from the camera), so both of my templates were 3 KB.

**Comment by especially-relative** [comment]
That worked! For some reason I had a clean copy of the templates as a png, which is much less likely to match. Thanks! :D
